name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies (with retry logic)
      run: |
        n=0
        until [ "$n" -ge 3 ]
        do
           npm install && break
           n=$((n+1))
           echo "npm install failed. Retrying... (Attempt $n of 3)"
           sleep 15
        done
        if [ "$n" -ge 3 ]; then exit 1; fi
      shell: bash

    - name: Run Build
      run: npm run build
